### ISSUE TITLE
Getting Thing Name & Variable Name in Dashboard template

### ISSUE THREAD

**Issue by mafzal9** [arduino/arduino-cloud-cli#140] opened 2023-09-14 19:03 UTC
Hi everyone,

we are working on the project where we want to generate the dashboard via command line. But when we extract the dashboard template it's giving Thing Name in the field of thing_id and Variable Name in the field of variable_id instead of Thing ID and Variable ID. already an issue is opened but still there is no updated. Would you please resolve the issue.

Best Regards,

**Comment by per1234** [comment] 2023-09-14 22:48
Closing as duplicate of https://github.com/arduino/arduino-cloud-cli/issues/96.

@mafzal9 high quality unique bug reports and feature requests are always welcome here, but please don't submit issues for bugs that are already being tracked.

**Closed by per1234** 2023-09-14 22:48 UTC
Labels: bug
